# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customerdistribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdistribution',
            old_name='customet',
            new_name='customer',
        ),
    ]
