# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20180102_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role_userinfo',
            field=models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='用户的角色'),
        ),
    ]
